### PR TITLE
Development fixes

### PR DESCRIPTION
**Pull request by lubieniebieski**
Hi, I just wanted to add a few lines of code to make development setup easier. I think, there should be some info in the readme file how to do the setup as well - I'm happy to make this change.

### CODE REVIEW

**Comment by andyw8** [comment]
Hi @lubieniebieski, thanks for this.

I hadn't realised that `config/database.yml` was missing, due to an entry in `.gitignore`. I've restored it in 40b0511. I'll look through the rest of your suggestions shortly.

**Comment by andyw8** [comment]
@lubieniebieski I've committed the missing ENV settings in 8e4385ed4b01cb7d23fdf982ab72164d09d1d65e, thanks for pointing that out.

**Comment by lubieniebieski** [comment]
ok, so I assume we might close this PR, or would you like me to resolve conflicts and work on this?

**Comment by andyw8** [comment]
Hi @lubieniebieski, if you can update it so that only `bin/setup` is left then I will merge that in, thanks.

**Pull request merged**
